---
- name: install certbot packages (Let's encrypt ssl certificates)
  dnf:
    name: ["python3-certbot", "python3-certbot-nginx"]
    state: latest
    update_cache: yes
  notify: reload nginx
  when: config_ssl == true

- name: run certbot cert generation and auto nginx config
  become: yes
  shell: "certbot --nginx --non-interactive --agree-tos -m {{ letsencrypt_email }} --domain {{ site_domain }}"
  when: config_ssl == true
  notify: reload nginx

- name: activate http2 protocol in nginx vhost config
  become: yes
  replace:
    path: "/etc/nginx/sites-available/{{ site_domain }}.conf"
    regexp: "^    listen 443 ssl; # managed by Certbot$"
    replace: "    listen 443 ssl http2; # managed by Certbot"
  when: config_ssl == true
  notify: reload nginx
  register: http2_debug

- name: add cron job for certbot renewal (if configured)
  cron:
    name: Certbot automatic renewal.
    job: "/usr/bin/certbot renew --quiet --no-self-upgrade"
    minute: "0"
    hour: "4"
    month: "*"
    user: "root"
  when: config_ssl == true
